// Created by szatpig at 2019/8/19.

const USER_TOKEN = 'USER_TOKEN';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const USER_LOGIN = 'USER_LOGIN';
const USER_MENU_LIST = 'USER_MENU_LIST';
const USER_LOGINOUT = 'USER_LOGINOUT';

const HEADER_COLLAPSED = 'HEADER_COLLAPSED';

const FETCH_ERROR = 'FETCH_ERROR';

export {
    USER_TOKEN,
    FETCH_ERROR,
    //request 请求
    LOGIN_REQUEST,
    USER_LOGIN,
    USER_MENU_LIST,
    USER_LOGINOUT,
    //header
    HEADER_COLLAPSED
}
